//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public string ScheduleName { get; set; }
        public int ScheduleTypeId { get; set; }
        public string WeekDays { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public bool StartAtOpen { get; set; }
        public bool EndAtClose { get; set; }
        public Nullable<int> DurationDays { get; set; }
        public Nullable<int> DurationHours { get; set; }
        public Nullable<int> IntervalHours { get; set; }
        public Nullable<int> IntervalDays { get; set; }
        public bool Recurring { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
