//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2MVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workgroup
    {
        public int Id { get; set; }
        public int ProgramAreaId { get; set; }
        public string WorkgroupName { get; set; }
    
        public virtual ProgramArea ProgramArea { get; set; }
    }
}
